% Auto-generated by stereoCalibrator app on 21-Jun-2017
%-------------------------------------------------------


% Define images to process
imageFileNames1 = {'C:\Users\payo\Downloads\fotosparstereo\cam1\calib01_cam01.jpg',...
    'C:\Users\payo\Downloads\fotosparstereo\cam1\calib02_cam01.jpg',...
    'C:\Users\payo\Downloads\fotosparstereo\cam1\calib03_cam01.jpg',...
    };
imageFileNames2 = {'C:\Users\payo\Downloads\fotosparstereo\cam2\calib01_cam02.jpg',...
    'C:\Users\payo\Downloads\fotosparstereo\cam2\calib02_cam02.jpg',...
    'C:\Users\payo\Downloads\fotosparstereo\cam2\calib03_cam02.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
squareSize = 2.350000e+01;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm');

% View reprojection errors
h1=figure; showReprojectionErrors(stereoParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

% You can use the calibration data to rectify stereo images.
I1 = imread(imageFileNames1{1});
I2 = imread(imageFileNames2{1});
[J1, J2] = rectifyStereoImages(I1, I2, stereoParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('StereoCalibrationAndSceneReconstructionExample')
